### ISSUE TITLE
get_interfaces_ip fails when multiple ipv6 addresses configured

### ISSUE THREAD

**Issue by ktbyers** [napalm-automation/napalm-nxos#127]
This was configured:

```
interface Ethernet2/4
  no switchport
  mac-address 2cc2.607d.5725
  ipv6 address 2001:db8:800:200c::2/64
  ipv6 address 2001:db8:800:200d::2/64
  no shutdown
```

Ansible playbook had the following:

```
    - name: NAPALM get interface config
      napalm_get_facts: 
        provider: "{{ creds_napalm }}"
        filter: "interfaces_ip"
```

Would get this error message back:

```
    "msg": "[interfaces_ip] cannot retrieve device data: 'list' object has no attribute 'split'"
```

Using NX-API
